name: My check

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: make install

      - name: Create .env file
        run: |
          cp .env.example .env || echo "APP_KEY=base64:$(openssl rand -base64 32)" > .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test
